language: python
matrix:
  include:
  - python: 2.7
    env:
    - TOX_ENV=py27
  - python: 3.4
    env:
    - TOX_ENV=py34
  - python: 3.5
    env:
    - TOX_ENV=py35
  - python: 3.6
    env:
    - TOX_ENV=py36
  - python: 3.7
    env:
    - TOX_ENV=py37
    dist: xenial
    sudo: true
install:
- pip install tox
script:
- tox -e $TOX_ENV

deploy:
  provider: pypi
  user: ellentao
  distributions: sdist bdist_wheel
  password:
    secure: "HrIPa6nOGZyBtX2gTSeDRR8Mcj1KzQ8bTI4qRoshOSxFcrMKAibBilaIQAgn8FjG8YQ9F9T1snLOPvXJhtzDOkpP0PzS4FVU4oOGVvVTnnlxTi/olT0Na432IcCMdeFlzOzqrF+p4uyDxgAxpoJTqYlTB8lqZRueSkL69WzC4JM="
  on:
    all_branches: true 
    repo: facebook/facebook-python-business-sdk
    # tags: true
    python: 3.7
    env: TOX_ENV=py37
