language: python
matrix:
  include:
  - python: 2.7
    env:
    - TOX_ENV=py27
  - python: 3.4
    env:
    - TOX_ENV=py34
  - python: 3.5
    env:
    - TOX_ENV=py35
  - python: 3.6
    env:
    - TOX_ENV=py36
  - python: 3.7
    env:
    - TOX_ENV=py37
    dist: xenial
    sudo: true
install:
- pip install tox
script:
- tox -e $TOX_ENV

deploy:
  provider: pypi
  user: ellentao
  password:
    secure: "kFqgTZvLaSbIbOJcmhQM8RMdefc+5SAH5J2fYGXvat2Tw6KVZXQhf9QAOG2lhHKAwDDXYsqsxGanngs27AtTVANHHi+eaf77VMFMIbO53y1imt95ZZ/TP3zAdMnf4ntKTTE1skcTE1az46jEwBqni4ONDm40lTol1dMfSzR8ZJ8="
  on:
    # tags: true
    distributions: sdist bdist_wheel
    all_branches: true
    repo: facebook/facebook-python-business-sdk
    python: 3.7
    env: TOX_ENV=py37
