language: python
matrix:
  include:
  - python: 2.7
    env:
    - TOX_ENV=py27
  - python: 3.4
    env:
    - TOX_ENV=py34
  - python: 3.5
    env:
    - TOX_ENV=py35
  - python: 3.6
    env:
    - TOX_ENV=py36
  - python: 3.7
    env:
    - TOX_ENV=py37
    dist: xenial
    sudo: true
install:
- pip install tox
script:
- tox -e $TOX_ENV

deploy:
  provider: pypi
  user: ellentao
  distributions: sdist bdist_wheel
  # repo: facebook/facebook-python-business-sdk
  password:
    secure: VZ4vocSufmh7xifDMIKwzZQlIgX+70JK3ks0Fa4nnuYWghqyqNI7UNEHa4Ij2AqU9s3ubiKdgmJyRzrnQVJ8OBCjp2WGeA/WW9FOgdEK/Eo2QiySiXZ6Lj/nQHNduDR+lKMzIWyH+ui6T36zCt546smkJHVHg1/YlG3cYk4E0Yw=
  on:
    all_branches: true 
    # tags: true
    python: 3.7
    env: TOX_ENV=py37
