language: python
matrix:
  include:
  - python: 2.7
    env:
    - TOX_ENV=py27
  - python: 3.4
    env:
    - TOX_ENV=py34
  - python: 3.5
    env:
    - TOX_ENV=py35
  - python: 3.6
    env:
    - TOX_ENV=py36
  - python: 3.7
    env:
    - TOX_ENV=py37
    dist: xenial
    sudo: true
install:
- pip install tox
script:
- tox -e $TOX_ENV

deploy:
  provider: pypi
  user: ellentao
  distributions: sdist bdist_wheel
  password:
    secure: "NYYJ+rOwcuxL4FMe5/5kAKYo3Je6QtGA3tRatraaiyjwzEkgTK4Q8E+wYi2RT2u7LW6x+hoIxzmGFctB86s91b2oj9W9TMNZazmha/il3UbIy46TEchxF3/9WAM0el2ZNQpvQ8A3ttsJdMGusxfYSMOsMBGEbRYgJPBSewz36mM="
  on:
    all_branches: true 
    repo: facebook/facebook-python-business-sdk
    # tags: true
    python: 3.7
    env: TOX_ENV=py37
